# Generated by Django 3.2.13 on 2022-10-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
