# Generated by Django 3.2.13 on 2022-10-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
